### ISSUE TITLE
Add an option to use virtual display for software rendering

### ISSUE THREAD

**Issue by sauk2** [gazebo-tooling/setup-gazebo#32]
Add an optional parameter `launch-virtual-display` to enable a virtual display for software rendering.

**Comment by j-rivero** [comment]
After discussing this offline with @sauk2 and the Gazebo team we do agree that this kind of configuration is better supported by declaring it at the runtime moment when the workflow needs it instead of trying to configure it during the whole setup creation of the environment. 

In this case probably has more sense to support it directly in a hypothetical action-gz-ci when running tests. I close the proposal by now.
